### ISSUE TITLE
Comment gets misassociated

### ISSUE THREAD

**Issue by tuncer** [tweag/ormolu#155]
before:
```
someVal :: String
someVal = "option1"
-- someVal = "option2"
-- someVal = "option3"

anotherVal :: String
anotherVal = "anotheroption0"
```

after:
```
someVal :: String
someVal = "option1"

-- someVal = "option2"
-- someVal = "option3"
anotherVal :: String
anotherVal = "anotheroption0"
```

**Comment by mrkkrp** [comment]
This is expected behavior right now and unlikely to change. Comments are already a very difficult thing to handle given how current GHC works. It's easy to see if you take a look at other tools and libraries like `ghc-exactprint`.

In short, comments that are "really" attached, in the sense that they use haddock syntax such as `-- |` and `-- ^` will not be "misassociated", other comments such as these, are more difficult and it's hard to guess what the author meant sometimes, so often they will be treated as preceding comments of function that follows them.

If you (or anyone else) feel like it, you're welcome to try to improve the situation and send a PR. Be prepared to suffer a physiological damage though.

**Comment by tuncer** [comment]
No worries, Haskell syntax (e.g. leading whitespace) is already hard to guess and format as intended by the author. Closing as hard to format correctly due to Haskell/haddock peculiarity.
