### ISSUE TITLE
Servant-style types become unreadable

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#171]
This is code from [wire-server](https://github.com/wireapp/wire-server/blob/develop/services/spar/src/Spar/API/Types.hs).

Before:

```haskell
type API
     = "sso" :> APISSO
  :<|> "sso-initiate-bind"  :> APIAuthReq  -- (see comment on 'APIAuthReq')
  :<|> "identity-providers" :> APIIDP
  :<|> "scim" :> APIScim
  :<|> OmitDocs :> "i" :> APIINTERNAL
```

After:

```haskell
type API
  = "sso"
    :> APISSO
      :<|> "sso-initiate-bind"
        :> APIAuthReq -- (see comment on 'APIAuthReq')
          :<|> "identity-providers"
            :> APIIDP
              :<|> "scim"
                :> APIScim
                  :<|> OmitDocs :> "i" :> APIINTERNAL
```

**Comment by mboes** [comment]
Ormolu shouldn't make *everything* multi-line just because there exists a newline: the general principle is that it should put newlines in the sibling nodes, but not the children nodes (unless the author requested them). However, to get this right, it would need to know about relative priorities of the involved operators (I hope it does already).

**Comment by mrkkrp** [comment]
>  it would need to know about relative priorities of the involved operators (I hope it does already)

No, it's much simpler right now. It knows not about fixities.

**Comment by utdemir** [comment]
As far as I understand, this situtation will not improve much even after implementing #259. It will get rid of those excessive indentation, but every operator will still introduce a newline since we do not know about the fixities.

Trying to learn the fixities would make Ormolu much more complex, since we then need to read our dependencies interface files to figure out the fixities. I do not think we would want to introduce this complexity. Is there anything else we can do to make this nicer?

**Comment by hovind** [comment]
> Trying to learn the fixities would make Ormolu much more complex, since we then need to read our dependencies interface files to figure out the fixities. I do not think we would want to introduce this complexity. Is there anything else we can do to make this nicer?

You may be aware, but [here](https://github.com/chrisdone/hindent/issues/392) is how `hindent` did it. :)

**Comment by mrkkrp** [comment]
I'm going to close this one since servant-style types are not so terrible anymore. The remaining issue is more general and is about determining precedence of operators in general. I'm going to create a dedicated issue for that.
