### ISSUE TITLE
Using "rec" as a name causes parse error

### ISSUE THREAD

**Issue by utdemir** [tweag/ormolu#173]
It looks like `rec` is a valid name without the `RecursiveDo` extension; and since `ormolu` has it enabled by default, it can fail on valid programs.

Valid program:

```
rec = rec
main = return ()
```
Ormolu output:

```
Parsing of source code failed:
foo.hs:1:1-3
parse error on input ‘rec’
```

Relevant: #163

**Comment by mboes** [comment]
@mrkkrp I guess this example shows that keyword-stealing syntax is unsafe to turn on. Because e.g. while `static foo` parses fine both with `-XStaticPointers` and without, `static` alone won't parse if it's turned on. Same with `rec`.

**Comment by int-index** [comment]
There are several files in GHC sources that fail because of this, either due to `rec` or `static`:

* `compiler/deSugar/Coverage.hs`
* `compiler/codeGen/StgCmmBind.hs`
* `compiler/codeGen/StgCmmTicky.hs`
* `compiler/nativeGen/RegAlloc/Liveness.hs`
* `compiler/nativeGen/RegAlloc/Graph/Spill.hs`
* `compiler/hieFile/HieAst.hs`
* `compiler/main/Elf.hs`
