### ISSUE TITLE
Ormolu messes up single-line let...where...

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#177]
Before:

```haskell
samples :: Int -> Gen a -> IO [a]
samples n (MkGen f) = do
    gen <- newQCGen
    let rands g = g1 : rands g2 where (g1, g2) = split g
    return $ [ f r i | i <- repeat n, r <- rands gen]
```

After (reported by Ormolu as unparseable because of `where`):

```haskell
samples :: Int -> Gen a -> IO [a]
samples n (MkGen f) = do
  gen <- newQCGen
  let rands g = g1 : rands g2
    where
      (g1, g2) = split g
  return $ [f r i | i <- repeat n, r <- rands gen]
```

**Comment by basile-henry** [comment]
It seems to be an issue with single line `let  ... in ...` as well:

```haskell
foo x = let x = z where z = 2 in x
```

With `ormolu -u`:

```haskell
foo x = let x = z
    where
      z = 2 in x
```

I had a look at the code and I think the issue comes from the fact that `where` is always formatted as multiline and `let` can have both single line and multiline versions. The way we select single versus multi line `let` is only by looking at the input and not at what the content (declarations) of the let gets formatted to.
So in this case `let` thinks it's single line because that's what the input says and then the `where` clause changes it to multi-line creating wrong output.

I see two different ways to resolve this issue:

1) We add support single line `where`. This should automatically fix the `let`/`where` interaction because you wouldn't be able to create a multi line `where` in a single line `let` manually.
2) We make the logic for `let` chose between single and multi line after the declarations get formatted.

I personally like the consistent multi-line aspect of the where clause, so maybe option 2 would be nicer. However I expect option 1 to be simpler to implement and give more freedom of style to the users so that might be the more sensible option. What do you think?
