### ISSUE TITLE
Crashes on unboxed string literals

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#187]
Input:

```haskell
{-# LANGUAGE MagicHash #-}
main = new "p"#
```

Output:

```
ormolu: Data.ByteString.ByteString.toConstr
CallStack (from HasCallStack):
  error, called at libraries/bytestring/Data/ByteString/Internal.hs:184:20 in bytestring-0.10.8.2:Data.ByteString.Internal
```

Surprisingly, the crash happens during sanity checking, not during formatting. `ormolu -u` works fine.

**Comment by mrkkrp** [comment]
This happens because `ByteString` defines `Data` instance manually and does not define `toConstr` which we use here:

https://github.com/tweag/ormolu/blob/bdb22b96ac114223f8de4ec6012390a8d238810c/src/Ormolu/Diff.hs#L54

The solution would be to somehow avoid invoking `toConstr` for `ByteStrings` I guess.
