### ISSUE TITLE
[|foo|] is turned into [e|foo|]

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#203]
`[|foo|]` and `[e|foo|]` are equivalent, but if it's impossible to distinguish between them at the AST level, perhaps at least the `[|foo|]` form could be considered the standard?

Alternatively you can look at the source text to distinguish them, I guess.

**Comment by basile-henry** [comment]
It's impossible to distinguish them at the AST level as far as I know:

https://github.com/tweag/ormolu/blob/a7265df09eebfbbc9f0235da03b0837afe922b56/src/Ormolu/Printer/Meat/Declaration/Value.hs#L779-L781

Threading the source along with the AST might be tricky, so I think we'll have to chose one version to default to.
I chose to default to `[e|` because it was more explicit but I don't feel strongly about either style. Whenever I write some TH, I end up putting the explicit `e` in expression quotes as soon as I write other types of quotes not far from it. But I can see the argument for leaving it out since it's the most common type of quote and most tutorials/examples don't write explicit `e`.

**Comment by aspiwack** [comment]
I think this may qualify as a bug of the GHC syntax tree. It's suppose to be as precise as possible a representation of what the programmer _actually wrote_.

So it's reasonable to file an issue against GHC (or better still a PR!) which add this piece of data. So that Ormolu can access this information in later versions of the GHC API.

**Comment by utdemir** [comment]
It looks like this information is available in annotations, so we can preserve what user wrote originally. I opened [a PR](https://github.com/tweag/ormolu/pull/306) doing that.

However, personally I think there is value to sticking to a single style, and personally I would prefer the explicit one (`[e|`).
