### ISSUE TITLE
Idempotence is broken for an example involving operators

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#273]
Discovered while fixing #260. Here is an example derived from existing tests:

```haskell
foo =
  bar
  ++
    {- some comment -}
    case foo of
      a -> a
```

this becomes after first run:

```haskell
foo =
  bar
    ++ {- some comment -}
    case foo of
      a -> a
```

if we run Ormolu once again however, we get:

```haskell
foo =
  bar
    ++ case foo of {- some comment -}
      a -> a
```

**Comment by utdemir** [comment]
As far as I can understand, the issue is that, at the first run, the comment is attached to the `case` expression, so we print it hanging after `++` operator; but then on the second run Ormolu thinks it is attached to `++`, so it hangs the `case` expression and prints the comment at the newline. 

I couldn't figure out a good solution for this. Only thing I was able to figure out is to stop comments attaching to infix operators, which solved this issue but I am not quite happy with that solution. You can look at this solution on the branch "[ud/dont-attach-comments-to-operators](https://github.com/tweag/ormolu/compare/ud/dont-attach-comments-to-operators)".

It feels to me like if we keep putting comments to arbitrary locations we will keep having these kind of problems. Maybe we should have a combinator to mark safe locations to put a comment, and then only use those to insert comments. Although I am not sure how easy that would be.

**Comment by utdemir** [comment]
This issue is quite tricky. Currently we attach comments to AST nodes based on a bunch of non-trivial rules, and having those rules give the exact same answer after formatting is hard; and the fact that inserting comments can affect the formatting makes it even harder.

I can not figure out an easy solution without having to implement special logic designed to play well with our formatting.

I am now trying a different approach where I first format the code without regarding comments, and then inject the comments to the formatted source code on a second pass. The main premise is that; we do not actually comment AST element, we comment a line of source code. If we figure out where that line of code corresponds to on the formatted text, we can insert the comment there in the same way without having to necessarily attach them to an AST element.
