### ISSUE TITLE
Split examples into smaller ones

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#312]
There has been a lot of good intense work lately and as a result of that some examples have grown considerably. The problem is that we do not show diffs when something is not formatted as expected, we show entire "expected/got" files. It works well when files are small, but not so well where they are huge (some of our examples are well beyond 100 lines). It can be hard to understand where the problem is.

This task is about splitting bigger examples (longer than 20 lines I'd say) into smaller ones. It's a good idea to create new sub-directories and name each file in a meaningful way.

**Comment by utdemir** [comment]
While implementing this change I had to make quite a bit of arbitrary decisions about how to split and name examples, since:

* More interesting examples usually consist of many different syntactical constructs, and it is hard to categorize them unber a single construct.
* We sometimes have many similar examples under the same name, and collectively they take many lines; but sometimes there is no meaningful distinction between them, so I have to split them arbitrarily and use names like `rewrite-rule1`, `rewrite-rule2` etc.

I am still going to open a PR with my changes, but I will suggest an alternative approach. We can stop naming or categorizing the examples, and dump them all to a single directory with auto-generated names (`T00001.hs`, `T00002.hs`...). This would make adding and updating examples quite easy. And I don't think maintaining them will be hard since we can just re-format everything on code changes and look at the `git diff` output. And, for some reason if we want to look at examples of a specific construct, we can easily write a small application which parses the test cases and returns the ones containing the specified construct.

**Comment by mrkkrp** [comment]
> This would make adding and updating examples quite easy

Is it that coming up with a good name is the difficulty you want to solve? It doesn't appear problematic to me, and numbers still can be used.

> we can just re-format everything on code changes and look at the git diff output

We can do the same with the current approach as well.

> for some reason if we want to look at examples of a specific construct, we can easily write a small application which parses the test cases and returns the ones containing the specified construct.

We also can do the same with current approach.

If we summarize your proposition, it looks like it

* Pros: doesn't require us to come up with names for examples or categorize them.
* Cons: We won't be able to tell what is covered and what is not. In fact, the only thing that we'll be able to do is to grow the collection of tests as we discover new problematic cases. (Which is pretty much how we already work.)

I don't think the re-organization will bring us new problems, but it doesn't look that coming up with names is problematic either.

**Comment by mrkkrp** [comment]
I'm not against the change @utdemir proposes. If everyone is OK with it I'd merge a PR implementing that.
