### ISSUE TITLE
Figure out a way to deal with precedence of operators

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#315]
To achieve good formatting of code with many operators with different precedence it looks like we'll need to know precedence of every operator.

So far the alternatives I know about are:

* Hard-coding knowledge of precedence of certain operators (Hindent).
* Making this info part of a config (Birttany). Will be difficult for us, as we don't have any config!
* Trying to learn from GHC actual info about operators. Probably complicated and won't allow us to format a file without knowing anything about its project and environment, which is a handy thing.
* Try to figure out precedence from original formatting. Needs investigation.

**Comment by mboes** [comment]
> Try to figure out precedence from original formatting. Needs investigation.

The latter option sounds more in the spirit of Ormolu. It's hard to guess what expressions should be multi-line, so we let the user decide. It's hard to identify which operators are higher precedence, so we can let the user tell us.

**Comment by mrkkrp** [comment]
Here is what I think could work well.

At first GHC parser parses all operators as associating the same way with the same precedence (I do not remember which fixity is used, but it doesn't really matter). This is why things get “mis-parsed” and so when start/end positions of operator's arguments are combined, the result is always a
multi-line span and we end up putting each operator on its own line.

Fixing this mess is done later in GHC, is renamer's job and for that it needs to know precedence and fixities of operators. We could leverage this in the following way:

* Introduce an additional processing step right after parsing.
* Traverse the entire AST perhaps using `syb` with the goal of assigning precedence to various operators we encounter in the AST:
  * Whenever `AppOp` thing is found, record its location and operator symbol.
  * Do the same perhaps for type-level operators.
  * Identify clusters of nested operators using the location information.
  * Assign higher precedence to operators (they bind tighter) that tend to stay on the same as opposed to those that span multiple lines and enclose them.
  * It doesn't matter that we won't arrive at exactly correct precedences and we still do not know anything about fixities as long as relative precedences that we deduce are good enough to bring some sanity in the output.
* Find the code in GHC that renamer uses to fix up operators. Use the inferred info and the code to correct the AST.
* The current printing code should "just work" after that.

**Comment by utdemir** [comment]
@mrkkrp What is the reason we do that in an another step instead of while printing? If I understand GHC's code correctly ([here](https://github.com/ghc/ghc/blob/9acba78004d4d4a149b9e1480d1d8c44b7a27cec/compiler/rename/RnTypes.hs#L1123)), fixities only matter when `OpApp`'s are immediate childs of each other. So, when pretty printing, as soon as we hit an `OpApp`, we can recursively gather all the immediate `OpApp` expressions, restructure the tree using the location information as you described and continue printing. This way we won't require another step over the whole AST.

The disadvantage is that we won't be able to use GHC's code for handling fixities; that seems to be hard because that function uses renamed AST (`LHsExpr GhcRn `) which I believe require a lot of additional information to create from the `LHsExpr GhcPs` we have.
