### ISSUE TITLE
Alignment influenced by input

### ISSUE THREAD

**Issue by cydparser** [tweag/ormolu#352]
I would like for "let some whitespace be programmable" to include whitespace used for alignment.

At work we align record definitions (::), record assignments (=), case expressions (->), multi-way if (->), and trailing comments (--). I find the aligned versions to be easier to skim and to spot bugs.

A simple algorithm to determine alignment:
1) For each line in a block, determine the column and padding (more than one space) of each alignable symbol
2) Check for two or more lines where the symbols are aligned and at least one of the symbols is padded with extra space

For example, the following would be aligned (arrows indicate the columns affected):
```haskell
case x of
  -- ↓    ↓
  Aa -> 1 -- ^
  B  -> 2 -- ^
  C -> 3  -- ^

case foo of
  -- ↓
  A -> 1 -- ^
  B  -> 2 -- ^
  Cc -> 3 -- ^
```

While the following would not be aligned:
```haskell
case x of
  A -> 1 -- ^
  B -> 2 -- ^

case x of
  A -> 1
  B -> 2
  Cc -> 3
```

**Comment by mrkkrp** [comment]
This was decided against because:

* Leads to diff amplification. Imagine you add a new case to a `case` expression and it happens to be longer than everything you have so far. What do you do? Well, you re-align all of them!
* Increases complexity of implementation (pretty sure it does).

**Comment by cydparser** [comment]
Whitespace changes can easily be ignored by common diffing tools and code review apps, so this isn't an issue for us.

Do you have a general idea of how much complexity would be added by this? I haven't looked at the source code yet. Would a pull request be welcome?

**Comment by mrkkrp** [comment]
I'd like to never align things because I'm too lazy to configure tools such as git to ignore whitespace-only changes. And I see those as changes anyway. So I'd like Ormolu to always remove the redundant alignment. Another thing is that we do not want to have any configuration for Ormolu, so there cannot be two different modes of operation.

But then, this is just my opinion, and although I lead development of the project, there are other users, who may have different needs. So I'm reluctant to close this one.

@mboes, what do you think about this?

**Comment by mboes** [comment]
I think that only the tool defaults are relevant to the discussion of diff amplification. Yes things can be be configured, but that's a hassle that the gains seem too modest to justify. Now, another reason for avoiding alignment is that it causes a lot of busywork when done by hand. If that busywork can all be automated away in a convincing way while still letting the user "program" where the alignment takes place convincingly, I say why not. We still have diff amplification, but at least the busywork goes away.

**Comment by utdemir** [comment]
I'm neither for or against this; but keeping alignment of operators can possibly also help #315.

But I agree that this increases implementation complexity considerably since many AST nodes contain some kind of alignable stuff and I can not see any uniform way to handle them. Also, I'm sure there are cases where the the AST does not expose locations of the symbols (for example `->`'s on cases, `|`'s on guards) and it'd be tricky to figure that out when printing.

**Comment by mrkkrp** [comment]
OK, after hearing everyone's opinion, it sounds to me that it is not worth the trouble.
