### ISSUE TITLE
Multi-line example with do block and lambda causing Ormolu to produce a different AST

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#381]
Here is an example extracted (simplified) from `capability` (not even `capability` itself, but from one of the examples):

```haskell
foo = catch
  do
     bar
     baz
  \e -> putStrLn $ "Too bad: " ++ show e
```

Ormolu fails to render something that parses to the same AST and instead outputs:

```haskell
foo =
  catch do
    bar
    baz \e -> putStrLn $ "Too bad: " ++ show e
```

...which is obviously a totally different expression.

When this is fixed, also add `capability` to the list of packages we check on CI, because it contains particularly fancy and hairy Haskell, so it makes for a good testing case.

**Comment by utdemir** [comment]
A similar example:

Before:

```haskell
foo = catch
  do
     bar
     baz
  end
```

After:

```haskell
foo =
  catch do
    bar
    baz
    end
```

The issue happens because we hang the second argument of a function application, however this breaks when there is a third argument.

The problem is that at the point we're printing the second argument we do not know whether there is a third argument or not, since the AST looks like `((f arg1) arg2)`. So we have to pass some information from the parent nodes to the child nodes to fix this.
