### ISSUE TITLE
Change the style of type signatures

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#389]
It was discussed off-line and we found that we're going to use this style:

```haskell
foo ::
  Foo ->
  Bar ->
  Baz
```

Because it plays nicer with advanced features of GHC Haskell and `forall`s. We'll also need to find a way to re-format `-- ^` Haddocks into `-- |` style and put them before arguments, not after.

**Comment by bjornbm** [comment]
I understand this is related to (and modifies the conclusions of) #148 and #382. Mentioning them here to get cross-references to/from those. For example, from the pull request (#392) I understand that the type synonym from #148 will now remain in its original form:

```hs
type CoerceLocalSig m m' =
  forall r a.
  LocalSig m  r a ->
  LocalSig m' r a
```

**Comment by mboes** [comment]
@int-index in #148, you argued for arrows on end of line. Could you tell us what style you use for argument comments? One casualty of end of line arrows is that one can no longer easily write the type of the argument + the associated docstring on a single line.

Before:

```
foo
  :: Int -- ^ First argument
  -> Char -- ^ Second argument
  -> String
```

After:

```
foo ::
  -- | First argument
  Int ->
  -- | Second argument
  Char ->
  String
```

**Comment by int-index** [comment]
Admittedly, I haven't given it much thought because I don't usually write per-argument Haddocks. Would something like this work?

```
foo ::
  Int {- | First argument -} ->
  Char {- | Second argument -} ->
  String
```

It's not perfect but it's on one line.

The multi-line version looks more readable to me, though (does it work?)

```
foo ::
  -- | First argument
  Int ->
  -- | Second argument
  Char ->
  String
```

If Haddock can deal with the multi-line version, I don't see a problem with it.

**Comment by neongreen** [comment]
I am in favor of the multi-line version. I am used to writing right-side hadocks (with `-- ^`), but I think it's actually a bad habit because it discourages more extensive documentation.

**Comment by mboes** [comment]
The multi-line version is accepted by Haddock, yes. I would prefer it over sticking comments *in the middle of* code. As I said - only downside is more verbosity. But if we can live with that, then great. @neongreen is saying multi-line is better than right-side haddocks anyways. All the better.

**Comment by nfrisby** [comment]
Just chiming in:

  * I much prefer having `->` at the end of the line; it feels right since `->` is right associative.
  * I'm very accustomed to `-- ^` comments inside of signatures. So I'd be surprised to see the `-- |` form, but it's something I would get used to.
  * I wouldn't expect but am too lazy to test that `Int {- | First argument -} ->` would work. Maybe `{- | First argument -} Int ->` would?

**Comment by mboes** [comment]
@nfrisby I don't think it will, but `Int {-^ first argument -}` will.

> I'm very accustomed to `-- ^` comments inside of signatures.

It would be nice if that worked. But if the `->` precedes the `-- ^`, then the docstring gets attached to the second argument, not the first. You're saying that you prefer EOL arrows. In that setting, how do you make `--^` work?

**Comment by nfrisby** [comment]
> You're saying that you prefer EOL arrows. In that setting, how do you make `--^` work?

I should have elaborated "Just chiming in" to "Just chiming in, I agree with every decision made above." :)

I do prefer EOL arrows, but despite that preference I haven't used them:

  * BOL arrows and trailing `-- ^` seems to be the de-facto standard, so I've used that instead of _rocking the boat_.

  * I merely shook my fist at Haddock when I first realized it choked on `-> -- ^ ...\n` instead considering other ways to do it. I didn't think of ` {- ^ ... -} ->\n`, and I assumed `-- | ` wouldn't work "inside" of a type.
