### ISSUE TITLE
Leave application operator ($) on the first line in multi-line expressions

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#390]
Currently a multi-line expression involving `($)` is reformatted like this:

```haskell
Foo $
  x + y

-- becomes:

Foo
  $ x + y
```

Which is arguably harder to read. It could be nicer to special-case `($)` and leave it on the first line.

**Comment by symbiont-chris-vogt** [comment]
I like it prefix as it is to be honest. We are doing that for `<>` and other things, too. And having `$` prefix allows understanding bracketing without having to scan to the end of the previous line.

**Comment by mrkkrp** [comment]
@symbiont-chris-vogt I guess your line of thinking is also valid. The issue is a matter of taste. So far I think most people are in favor of the change and I plan to implement it once I'm done with the change about type signatures.

**Comment by nfrisby** [comment]
[Idly chiming in again -- `ormolu` is poised to affect a lot of code, so I'm leveraging my current access to influence you :)]

Has the following been considered?

```
Foo $
Bar $
x + y
```

I think this is already a relatively common indentation idiom, and it seems reasonable given the typical use of `$` for "pipelines" and its right associativity (similar to the arguments for EOL `->`s in type signatures). The `$` operator is somewhat unique among operators since its primary use is simply to avoid having to nest parens.

Disclaimer: I haven't ever checked for corner cases that this sort of non-increasing indent can cause.

**Comment by mboes** [comment]
I agree with @nfrisby regarding `$` being a special-case, hence we shouldn't fear treating it as such.

**Comment by aspiwack** [comment]
The zero-indentation vertical layout will not typically work in a `do` instruction. (which doesn't mean that we shouldn't use the zero-indentation layout, just that we can't use it everywhere)

**Comment by mrkkrp** [comment]
> The zero-indentation vertical layout will not typically work in a `do` instruction.

There are enough special cases in the code as it is. I think we should just keep `($)` on the previous line without changing how indentation is bumped.
