### ISSUE TITLE
Extra newlines added in a comment

### ISSUE THREAD

**Issue by int-index** [tweag/ormolu#419]
Input:

```
-- The node can be in one of there states:
--
-- * Self-selection, collapsed.
-- * Self-selection, not collapsed.
-- * Child selection.
--
-- Note that a node with a child selected cannot be collapsed.
-- This way we can be certain that the selected node is visible.
data SelStatus = SelSelf Collapsed | SelChild
```

Output:

```
-- The node can be in one of there states:
--

-- * Self-selection, collapsed.

-- * Self-selection, not collapsed.

-- * Child selection.
--
-- Note that a node with a child selected cannot be collapsed.
-- This way we can be certain that the selected node is visible.

data SelStatus = SelSelf Collapsed | SelChild
```

The extra newlines, even if intentional, are not prefixed with `--`, so this looks like separate comments.

**Comment by mrkkrp** [comment]
Actually, this is not a bug. The `-- *` syntax can mean two different things:

* When used by itself, it's a section header.
* When used in the middle of a Haddock, it's part of bullet list.

When it's a header, we insert a newline before it for readability (and to prevent it from merging with previous haddock section and becoming an item in a bullet list, not a desirable transformation!). The problem is that in the case you show, you forgot the pipe `-- |`, so your haddock is not really a haddock, it's just a bunch of comment strings which are not attached to anything, thus the comments starting with `-- *` are in fact, headers! (Even haddock thinks so, try to generate haddocks for your original example.)

Try to run Ormolu on this for example:

```haskell
module Main where

-- | The node can be in one of there states:
--
-- * Self-selection, collapsed.
-- * Self-selection, not collapsed.
-- * Child selection.
--
-- Note that a node with a child selected cannot be collapsed.
-- This way we can be certain that the selected node is visible.
data SelStatus = SelSelf Int | SelChild

main :: IO ()
main = return ()
```

It should leave it unchanged.

**Comment by int-index** [comment]
> our haddock is not really a haddock, it's just a bunch of comment strings which are not attached to anything

I did not claim that this comment has any relation to Haddock – it is just a comment.

> The `-- *` syntax can mean two different things:

Yes, and in this comment it's an item in a bullet list.

Making this comment into a Haddock comment is a viable workaround, and yet I continue to believe this is a bug.

**Comment by mrkkrp** [comment]
> > The `-- *` syntax can mean two different things:
> 
> Yes, and in this comment it's an item in a bullet list.

It is clear to you and me, however the parser thinks it's `DocGroup`, see here: https://github.com/tweag/ormolu/blob/master/src/Ormolu/Printer/Meat/Declaration.hs#L95. This is the code that prints those `-- *` lines. If it was just a part of a comment, it would be printed differently. This is just how the input gets parsed, so as long as we use the GHC parser in Haddock extraction mode as our ground truth, it is a `DocGroup` thing.

**Comment by mrkkrp** [comment]
> Making this comment into a Haddock comment is a viable workaround, and yet I continue to believe this is a bug.

This or indent the list itself.

**Comment by int-index** [comment]
> the parser thinks it's `DocGroup`

> This or indent the list itself.

Sounds reasonable to me. Thanks.
