### ISSUE TITLE
Inconsistent style in the presence of leading $

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#424]
Code formatted with Ormolu:

```haskell
e1 =
  bar $
    if a
      then x
      else y

e2 =
  foo
    $ bar
    $ if a
      then x
      else y
```

I suspect that the second one is wrong, and should properly look like this:

```haskell
e2 =
  foo
    $ bar
    $ if a
        then x
        else y
```

**Comment by mrkkrp** [comment]
No, this is not wrong. This is how it should be. We cannot set indentation level to current column right after `$` because if we start doing that we'll have overly indented constructions in certain cases (such as with overly indented records if you remember that issue). This is as good as you can get.

**Comment by mrkkrp** [comment]
You can think of this as `then` and `else` being indented one level relative to `$` while the line with `if` stays "movable". In the same vein consider this:

```haskell
foo = if something
  then a
  else b
```

**Comment by neongreen** [comment]
Okay, makes sense.

```
e2 =
  foo
    >>##$@!! bar
    >>##$@!! if a
      then x
      else y
```
