### ISSUE TITLE
Minimize vertical space for single-constructor records

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#425]
The current style (A) for records is:

```haskell
data Foo
  = Foo
      { bar :: Bar,
        baz :: Baz
      }
```

I propose the following style (B) for single-constructor records:

```haskell
data Foo = Foo
  { bar :: Bar,
    baz :: Baz
  }
```

## Pros

* The most common style, according to Hackage grep.

* One-constructor records seem to stay one-constructor records so git diffs don't get worse. (Not sure about this one. Feedback welcome.)

* Slightly better use of horizontal space.

* Much better use of vertical space for `data`-heavy modules – important for people who split their screens horizontally instead of vertically.

## Cons

* Still, some diffs are inevitable. Especially annoying when the fields were heavily commented and you have to rewrap the comments.

## Unresolved questions

* Should (A) be reformatted into (B)? "Yes" seems like a good answer, but it would be slightly unfortunate if it was impossible to break a `data ReallyReallyReallyReallyLongName = ReallyReallyReallyReallyLongName ...` even when requested by the programmerr.

**Comment by neongreen** [comment]
Regarding the unresolved question: on the other hand, "no" is consistent with an existing decision Ormolu makes: both (C) and (D) are accepted by Ormolu and neither is formatted into the other.

```haskell
-- (C)

foo = bar $ \x ->
  baz
```

```haskell
-- (D)

foo = 
  bar $ \x ->
    baz
```

**Comment by mrkkrp** [comment]
I'm going to implement this now.

**Comment by mrkkrp** [comment]
This requires a lot of ugly code. Maybe our present formatting is not that bad? After all, it's very consistent and there is no question whether to format A into B or not. With C and D we *had* to do it this way because otherwise the transformation would be not idempotent.

I'm not super convinced that this change is necessary. I will not implement this change myself, but if someone implements it, I'll review.

**Comment by mboes** [comment]
Could you say more about the "ugly code"? I find it suspicious that a style change like the one requested would cause such difficulty. Perhaps a sign that better formatting combinators are needed?

**Comment by mrkkrp** [comment]
Not really a "lot" but uglier than it is to the point I decided to use my Ormolu time differently. It needs to do additional calculation to decide when to insert a newline and that should be only for single constructor records in Haskell98 style and then we should pass a flag to the code that renders data constructors because that also should be different.

**Comment by torgeirsh** [comment]
By the way, is it necessary to hang the opening curly brace into the indentation? It makes it difficult to change indentation width using simple search and replace.
