### ISSUE TITLE
Ormolu cannot parse files with broken Haddocks

### ISSUE THREAD

**Issue by cdsmith** [tweag/ormolu#432]
This parses and runs just fine in GHC, but Ormolu gives an error.

```
-- | A comment

import Data.Maybe

main = return ()
```

The haddock comment is orphaned, of course, but this is still valid Haskell code!

**Comment by neongreen** [comment]
This happens because Ormolu always runs GHC in "Haddock mode" – detecting Haddock comments is the GHC parser's job, surprisingly.

It could easily be fixed by running parsing twice, with and without `Opt_Haddock`, but this would mean that users would get wildly different formatting depending on whether they have broken Haddocks in the file or not. So at the very least they should be warned that they have broken Haddockcs.

I suspect that running Ormolu via format-on-save won't care to display any warnings Ormolu cares to throw, so it's not a good solution in general.

However, a flag `--tolerate-broken-haddock` might be reasonable to have if you're controlling the environment (CodeWorld?) and can ensure the warnings don't get silenced.

**Comment by mrkkrp** [comment]
I'm having hard time imagining how this could work. Parsing with and without Haddocks extraction is very different, leading to different spans and different ASTs. We've put a lot of effort and hours of work into supporting the mode with Haddock extraction because that's more valuable and is totally worth the cost of being a bit more strict about the input source code.

**Comment by neongreen** [comment]
I thought parsing without Haddock extraction was just disabling `Opt_Haddock`? Then GHC would provide docstrings as comments instead of dedicated AST nodes.

Or is it more complicated that that?

**Comment by mrkkrp** [comment]
Yes, but we're not prepared to render them properly if they end up as simple comments now. They are expected to be in the AST.

**Comment by mrkkrp** [comment]
The point here is that it's fairly hard to make both modes to coexist. It took me a long while to rework it to support the parsing mode with Haddock extraction. It is a nightmare to imagine that we could support both modes. We would need to test two different Oromolus, basically. Not worth it.
