### ISSUE TITLE
Idempotence bug with comments in data declaration

### ISSUE THREAD

**Issue by judah** [tweag/ormolu#449]
Input:
```
data A =
     B  -- C

   -- D
   | E
```

Output:

```
Formatting is not idempotent:
  before: " B -- C\n  | -- D\n   "
  after:  " B -- C\n    -- D\n  |"
Please, consider reporting the bug.
```

Investigating further, it formats it as:

```
data A
  = B -- C
  | -- D
    E
```

which then gets reformatted as:

```
data A
  = B -- C
    -- D
  | E
```

**Comment by mrkkrp** [comment]
Some notes (mostly for myself):

* The first transformation that puts `-- C` and `-- D` on adjoined lines appears valid to me. This happens because printing of `|` erases the `SpanMark` left by `-- C` and it makes it possible to put `-- D` without an extra newline to separate the two comments.
* The second transformation is however problematic. Mostly because `|` is probably not reflected in the span stream and `-- D` is considered as a continuation of `-- C` contrary to the logic of the previous step (where we concluded that it's safe not to insert a blank line between the two comments).

Solution is not clear. Need to check whether there is indeed no way to detect `|` in that case.
