### ISSUE TITLE
Group certain top-level type signatures?

### ISSUE THREAD

**Issue by amesgen** [tweag/ormolu#466]
This

```haskell
clientFunc1 :: SomeType1
clientFunc2 :: SomeType2
clientFunc3 :: SomeType3
clientFunc1 :<|> clientFunc2 :<|> clientFunc3 = hoistClient foo bar baz
```
is reformatted to
```haskell
clientFunc1 :: SomeType1

clientFunc2 :: SomeType2

clientFunc3 :: SomeType3
clientFunc1 :<|> clientFunc2 :<|> clientFunc3 = hoistClient foo bar baz

```
which is not perfect IMHO (in particular with more `clientFunc`s).

**Comment by mrkkrp** [comment]
The current logic (implemented in #327) works like this:

* Take first declaration as a header and see which function names it contains.
* For everything that follows: if it mentions one of the names from the header, then it's grouped together with the header.
* If it is related to the definition that directly precedes it, then group it with that definitions.

This allows us to handle these cases respectively:

```haskell
foo, bar :: Int
foo = 10
bar = 20

baz :: Int
baz = 42
```

The challenge to add support for your case is that when we see type signatures they all look unrelated to each other and we cannot know that there will be a function definition that will actually make the whole block of declarations related to each to other.

Except that perhaps we do. It seems like we cannot squeeze an unrelated signature between type signatures and type definitions of a block. That means that we could do the following:

* Remember function name that the first declaration mentions.
* If we run into a different signature (or actually it could be a pragma or something), we also remember its name by adding it to the pool of "unresolved names".
* There must be corresponding function definition (otherwise it's not valid Haskell code), and it must go right after the signature, so we keep grouping definitions together until all the names in the pool of unresolved names are "discharged" by actual definitions.
* At the same time we must still group together consecutive definitions mentioning the same function name.

I'll try to implement this logic and we'll see how it goes.

**Comment by neongreen** [comment]
Or we can topologically sort all declarations everywhere, which will also automatically solve cases like type signatures following declarations in classes (apparently this is allowed).

**Comment by neongreen** [comment]
By "topologically sort" I mean that we can define a relation like "A should precede B" (signatures should precede function bodies, inline pragmas should go after function bodies, etc) and automagically get the right grouping from this.

As long as we use a stable sort, it won't mess the order of declarations. I don't know if the sort in Data.Containers is stable (https://hackage.haskell.org/package/containers-0.6.2.1/docs/Data-Graph.html#v:topSort), but finding the right one is not hard.

**Comment by neongreen** [comment]
It's questionable whether we want to move _towards_ reshuffling user code and not _away from it_, given #74.

**Comment by amesgen** [comment]
I guess that the situation above is relatively rare (I only use it for servant client declarations), so it won't prevent a lot of people from adoption. But it should definitely taken into consideration how to handle whitespace and (even more important) comments / doc strings.

IMHO moving type signatures which are below their respective declaration is a good idea.

`topSort` seems to traverse neighbor nodes in reverse order, so it should be usable for this purpose:
```haskell
 Λ :{
 > quickCheck do
 >   nums <- hashNub <$> listOf1 do choose (2,100)
 >   let (graph, nodeFromVertex, _) = graphFromEdges $ [(0,0,nums),(1,1,[])] ++ (nums <&> \n -> (n,n,[1]))
 >   pure $ (graph & topSort <&> nodeFromVertex <&> view _1) == ([0] ++ reverse nums ++ [1])
 > :}
+++ OK, passed 100 tests.
```
