### ISSUE TITLE
Support rendering of remaining types of expressions

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#47]
Some types of expressions are not implemented yet. For example `do`-notation. Extend the `p_hsExpr` function in `Ormolu.Printer.Meat.Declaration.Value` to support all of them.

**Comment by yumiova** [comment]
Pretty printing of expressions is something I have been working on in [yumiova:yumiova/misc-expression](https://github.com/yumiova/ormolu/tree/yumiova/misc-expression). I forgot to mention this up until now.

Basically, I am more or less done with _most_ types of expressions. Some expressions need some more thought; I will be sending a pull request with information about this soon.

**Comment by ruhatch** [comment]
@yumiova are you taking on `do`-notation yet, or can I claim that and track it in another issue?

**Comment by mrkkrp** [comment]
There is an attempt to implement it in #60, but that will require some adjustments.

**Comment by yumiova** [comment]
@ruhatch After seeing the work of #60 in supporting do notation, I intended to wait and see what happens. Once do notation is figured out, I would like to explore implementing list comprehensions and arrow notation. I have no intention of implementing Template Haskell splices and brackets.

**Comment by ruhatch** [comment]
Ah, okay! Might there be a simpler way to get a birds-eye view of what's been covered? Maybe something in the readme or wiki that links the issues?

**Comment by mrkkrp** [comment]
Maybe we could have an umbrella issue with a list of checkboxes. When the entire AST is covered the issue can be closed. I'll probably create it this evening.

**Comment by mrkkrp** [comment]
Now that I merged #60 what remains here is various not-yet-covered types of do notation (includes arrow notation, comprehensions, etc.) and perhaps something in the `p_hsExpr`.

**Comment by yumiova** [comment]
My work on pretty printing list comprehensions and arrow notation will have to be delayed just a little bit. Mainly because I am working on #79, as well as upcoming exams I need to practice for. Consequently, I will only be able to work on list comprehensions around the coming friday/saturday. If anyone needs list comprehensions and/or arrow notation before then, the prompt is open. Otherwise, I will definitely get it done by saturday.

**Comment by yumiova** [comment]
Pretty printing of parts of list comprehensions will finally get implemented with #119. This does not, however, include transform list comprehensions, largely because dealing with that well is much trickier. See #119 for more information. Unless someone else does it or someone explicitly presents a case where they have use for it, I will probably wait for _a long time_ before implementing transform list comprehensions, as it otherwise really does not seem important to me.

Otherwise, arrow notation will likely be implemented by the end of the week.

**Comment by mboes** [comment]
> I will probably wait for a long time before implementing transform list comprehensions

That seems very reasonable to me. They are very seldom useful. @mrkkrp this illustrates the need for identity printers: some parts of the AST are not worth the effort to implement pretty-printing for, but at the same time it would be very annoying to the user if Ormolu just crashed and did nothing with the 99% of the remaining code in the file, which it *can* format.

**Comment by domenkozar** [comment]
Missing:

- [ ] RecStmt
- [ ] XStmtLR
- [ ] ApplicativeStmt
- [ ] TransStmt

**Comment by mrkkrp** [comment]
Anyone to pick up `ApplicativeStmt` and `TransStmt`?

**Comment by yumiova** [comment]
I can work on `TransStmt` (e.g. transform list comprehensions) by the end of the week.

**Comment by mrkkrp** [comment]
@yumiova Sounds good, thanks!

**Comment by mrkkrp** [comment]
For the record, `VarBr` seems to be missing as well. I tried to run `ormolu` on some real code and it failed because of `VarBr`.

**Comment by mrkkrp** [comment]
Now only `ApplicativeStmt` remains. After that we'll have covered the entire AST!

**Comment by aspiwack** [comment]
Is that in the do notation? I don't believe there is a syntax for applicative statements. They are solely created (I think) by `-XApplicativeDo`.

**Comment by mrkkrp** [comment]
I don't know yet, but there is the `ApplicativeStmt` data constructor, which should be there for a reason. Thus, it's possible that we'll need to cover it somehow.

**Comment by mrkkrp** [comment]
`ApplicativeStmt` thing is generated by renamer. It's of no interest to us. Thus, this issue is resolved.
