### ISSUE TITLE
Preserve leading whitespace

### ISSUE THREAD

**Issue by mitchellwrosen** [tweag/ormolu#483]
If I have a file like:

```
foo = do
  bar baz
```

and then (in vim) visually highlight the `bar baz` to run through ormolu, it will leave my file as

```
foo = do
bar baz
```

Is it possible to preserve leading whitespace for this use case?

**Comment by utdemir** [comment]
Ormolu is designed to format the whole module, not a part of it. Since it works by parsing and pretty printing the AST, it simply lacks context to parse `  bar baz` correctly. 

You might get lucky and get a sensible formatting if you format the whole top-level declaration (two lines you posted above), but really it would be much better if you just pass the whole file.

**Comment by mrkkrp** [comment]
Closing in favor of #572.
