### ISSUE TITLE
Commenting last set of ADT constructors breaks ormolu

### ISSUE THREAD

**Issue by srid** [tweag/ormolu#489]
For this code:

```haskell
data Foo
  = Bar
  -- | Baz
  deriving (Show)
```

Ormolu will fail:

```
Parsing of source code failed:
  /dev/stdin:34:3-10
  parse error on input `deriving'
```

**Comment by utdemir** [comment]
`-- |` string denotes a Haddock comment, but used in a wrong place in this case. 

Quoting @mrkkrp from [another issue](https://github.com/tweag/ormolu/issues/480#issuecomment-562966292):

> It should be obivous that Ormolu has to work with Haddocks. Both Ormolu and the Haddock executable use GHC parser with a special setting to extract Haddocks. The thing is, though, that once this setting is activated, the input must form a finished Haskell module with correct Haddocks, otherwise it is a parse error.

It's a bit unfortunate that Ormolu fails in a correct Haskell program, but there is nothing much it can do since it is also responsible for reformatting Haddock comments too. A temporary solution in this case would be putting one more space before `|` so that it is not recognized as a Haddock comment.

**Comment by mrkkrp** [comment]
Yeah, as @utdemir point out, this is just not a valid input for GHC in Haddock mode and there is little we can do.
