### ISSUE TITLE
Implement rendering of type class and instance declarations

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#49]
Extend `p_tyClDecl` and `p_hsDecl` in `Ormolu.Printer.Meat.Declaration` in order to support type class and instance declarations.

**Comment by yumiova** [comment]
I have a working prototype of type class (and type family) instance declarations in [yumiova:yumiova/instance-declaration](https://github.com/yumiova/ormolu/tree/yumiova/instance-declaration). It is not, however, something I consider currently ready for merging.

**Comment by yumiova** [comment]
OK, I am more or less done with the definition of instance declarations (aside from perhaps adding more tests.) I also ended up implementing associated types, which made it seem natural to implement type family instances as well. However, I have not implemented associated data types. Such a change would either require code duplication or a slightly invasive change to `p_dataDecl`.

If you want, I can send a pull request for this individually. It makes no difference to me, since I want to try to implement type class declarations regardless. Either both can be implemented in one great pull request, or it can be two separate pull requests.

Also, looking at the forks, it seems like @fghibellini has a [branch](https://github.com/fghibellini/ormolu/tree/instance-decls) that works on the same thing? I hope I haven't accidentally caused some misunderstanding by not mentioning my interest in this soon enough.

**Comment by mrkkrp** [comment]
I'd encourage you to send PRs with ready bits as soon as possible.

**Comment by yumiova** [comment]
I am currently working on type class declarations in [yumiova:yumiova/class-declaration](https://github.com/yumiova/ormolu/tree/yumiova/class-declaration).

**Comment by mrkkrp** [comment]
Right now, what remains to implement for this one is just type class declarations.

**Comment by mrkkrp** [comment]
Done in #79.
