### ISSUE TITLE
Extra space with negation operator

### ISSUE THREAD

**Issue by brandon-leapyear** [tweag/ormolu#694]
**Describe the bug**

**To Reproduce**
```hs
f x = 1 / (1 + exp (-x))
```
gets reformatted as
```hs
f x = 1 / (1 + exp (- x))
```

Apparently GHC still treats this as equivalent, but it's very easy to mistakenly read it as a partially applied `-`

**Expected behavior**
`(-x)` should kept as `(-x)`

**Environment**
 - OS name + version:
 - Version of the code:

**Additional context**

**Comment by mrkkrp** [comment]
I don't consider this a bug. I wonder if we should keep this open.

**Comment by brandon-leapyear** [comment]
Sure, this could be considered a feature request. I think this is a worthwhile issue, though, because `(- x)` very much looks like a partial section, not a unary operator

**Comment by mrkkrp** [comment]
But `(-x)` and `(- x)` are parsed as identical constructs on the AST level, right?

**Comment by brandon-leapyear** [comment]
Yes, but the point of a formatter is to enforce consistent style **for the sake of readability** across a codebase. IMO, `(- x)` is much less readable than `(-x)`, and the formatter should style in the more readable format

**Comment by brandon-leapyear** [comment]
Adding on to this, 
```hs
f n = n-1
```
gets reformatted to
```hs
f n = n -1
```
Distinguishing between negation operator and minus would be nice

**Comment by amesgen** [comment]
The reason why ormolu adds spaces after `-` is due to #181: [`NegativeLiterals`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/exts/negative_literals.html#extension-NegativeLiterals) is not part of `manualExts`, so the expressions `-1` and `- 1` as parsed via ormolu without further options have differing ASTs (the literal `-1` and the negated literal `1`). Without `NegativeLiterals`, they would have the same AST. In all other places, the space after the `-` is not necessary.

In #734, I added `NegativeLiterals` to `manualExts`, and only add a space after `-` if we negate a literal and `NegativeLiterals` is actually enabled.

This means that

```haskell
f x = 1 / (1 + exp (-x))
```

is a fixed point, and 

```haskell
f n = n-1
```

is formatted into 

```haskell
f n = n - 1
```

---

As a side note: GHC 9.0 added the new extension [`LexicalNegation`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/exts/lexical_negation.html#extension-LexicalNegation) which allows `(- x)` to be an operator section, such that

```haskell
{-# LANGUAGE LexicalNegation #-}

add2AndSubtract3 :: Bifunctor f => f Int Int -> f Int Int
add2AndSubtract3 = bimap (+ 2) (- 3)
```

is a fixed point, and `add2AndSubtract3 (1,2) == (3,-1)`. Without `LexicalNegation`, the code would be formatted to 

```haskell
add2AndSubtract3 :: Bifunctor f => f Int Int -> f Int Int
add2AndSubtract3 = bimap (+ 2) (-3)
```

which makes it easy to spot that something is wrong.
