### ISSUE TITLE
Misplaced `($)`.

### ISSUE THREAD

**Issue by alissa-tung** [tweag/ormolu#699]
**To Reproduce**
```haskell
issue :: IO ()
issue = do
  undefined $undefined $
    undefined
      undefined
      ++ undefined
      ++ undefined
```

**Expected behavior**
```haskell
issue :: IO ()
issue = do
  undefined $ undefined $
    undefined
      undefined
      ++ undefined
      ++ undefined

```

**Environment**
 - Arch Linux x86_64 + 5.11.13-arch1-1
 - HLS   1.0.0 & code 1.56.0-insider

**Comment by mrkkrp** [comment]
Not a bug, `$undefined` is parsed as a TH splice. Add a space between `$` and `undefined` if you want `$` to be an operator. Then I get:

```haskell

```

**Comment by mboes** [comment]
Shouldn't the way this is parsed depend on whether Template Haskell is turned on?

**Comment by mrkkrp** [comment]
I think TH is enabled by default for convenience.

**Comment by alissa-tung** [comment]
Sorry, thx.

**Comment by mboes** [comment]
Yes, but I would argue that it should not. It changes the semantics of existing syntax, as this example shows. `-XTypeApplications` is already disabled for the same reason. Further, enabling TemplateHaskell in a `package.cabal` for all modules is never a good idea, because the use of Template Haskell pessimizes GHC recompilation checking. See https://gitlab.haskell.org/ghc/ghc/-/issues/18711 and https://gitlab.haskell.org/ghc/ghc/-/issues/8211. So users enabling TemplateHaskell globally is essentially a bug, and we shouldn't encourage it. Therefore, it's fine for Ormolu to fail to parse when Template Haskell features are being used without a `LANGUAGE` pragma.

**Comment by mrkkrp** [comment]
Okay, adjusted in #702.
