### ISSUE TITLE
Record updates with RDP are not idempotent

### ISSUE THREAD

**Issue by neongreen** [tweag/ormolu#701]
```haskell
{-# OPTIONS_GHC -fplugin=RecordDotPreprocessor #-}

a =
  def{ N.k = g
     }
```

Invoking ormolu-0.1.4.1 results in:

```haskell
{-# OPTIONS_GHC -fplugin=RecordDotPreprocessor #-}

a =
  def
    { N.k = g
    }
```

Invoking ormolu-0.1.4.1 again results in:

```haskell
{-# OPTIONS_GHC -fplugin=RecordDotPreprocessor #-}

a =
  def{N.k = g
     }
```

**Comment by davidmrt98** [comment]
The underlying issue seems to be that in some cases Ormolu transforms a "RDP style" record update (no space before the open brace) into a "regular" record update. 

A minimal example:
```hs
{-# OPTIONS_GHC -fplugin=RecordDotPreprocessor #-}

b{ c = d}
```
gets formatted to
```hs
{-# OPTIONS_GHC -fplugin=RecordDotPreprocessor #-}

b {c = d}
```
More specifically, this bug occurs if there is whitespace **after** the open brace.

I am new to the Ormolu code base but if nobody else is already working on this, I would like to have a try at fixing the bug.

**Comment by mrkkrp** [comment]
You are welcome to try to fix it. Otherwise, we hope to have an intern working on Ormolu soon.

**Comment by neongreen** [comment]
> if nobody else is already working on this

Nobody is working on this from the Monadfix side, at least.
