### ISSUE TITLE
AST differs on promoted infix data constructor

### ISSUE THREAD

**Issue by evanrelf** [tweag/ormolu#768]
**Describe the bug**
`ormolu` chokes on promoted infix data constructors.

**To Reproduce**

```bash
$ echo "type X = () '`PromotedInfix` ()" | ormolu
<stdin>
  AST of input and AST of formatted code differ.
    at <stdin>:1:10-31
  Please, consider reporting the bug.
```

**Expected behavior**
`ormolu` handles promoted infix data constructors.

**Environment**
 - OS name + version: NixOS 20.03
 - Version of the code: `ormolu` 2.0.0.0

**Comment by amesgen** [comment]
Thanks! This seems to be an upstream issue in GHC/ghc-lib-parser: Applying the diff

```diff
diff --git a/src/Ormolu/Printer/Meat/Common.hs b/src/Ormolu/Printer/Meat/Common.hs
index 5a3e6b1..b365890 100644
--- a/src/Ormolu/Printer/Meat/Common.hs
+++ b/src/Ormolu/Printer/Meat/Common.hs
@@ -19,6 +19,7 @@ where
 import Control.Monad
 import Data.List (isPrefixOf)
 import qualified Data.Text as T
+import Debug.Trace
 import GHC.Hs.Doc
 import GHC.Hs.ImpExp
 import GHC.Parser.Annotation
@@ -60,6 +61,7 @@ p_ieWrappedName = \case
 p_rdrName :: Located RdrName -> R ()
 p_rdrName l@(L spn _) = located l $ \x -> do
   ids <- getAnns spn
+  traceShowM (showOutputable (unLoc l), showOutputable ids)
   let backticksWrapper =
         if AnnBackquote `elem` ids
           then backticks
```

to 46a3142fce77b3e7a2788820e2bc841e79040da7, we get the output 

```
("PromotedInfix","[AnnSimpleQuote, AnnVal]")
```

which does *not* contain [`AnnBackquote`](https://hackage.haskell.org/package/ghc-lib-parser-9.0.1.20210324/docs/GHC-Parser-Annotation.html#v:AnnBackquote), which explains why your example
```haskell
type X = () '`PromotedInfix` ()
```
is formatted (with `--unsafe`) into
```haskell
type X = () 'PromotedInfix ()
```
due to this code not firing:

https://github.com/tweag/ormolu/blob/46a3142fce77b3e7a2788820e2bc841e79040da7/src/Ormolu/Printer/Meat/Common.hs#L64-L66

---

I can try to find a workaround, but upgrading to ghc-lib-parser-9.2 (which should not be that far away from now) should also fix this automatically.

**Comment by mrkkrp** [comment]
I agree, let's wait for 9.2.
