### ISSUE TITLE
Bug: Quoting patterns doesn't work

### ISSUE THREAD

**Issue by shinzui** [tweag/ormolu#772]
**Describe the bug**
Quoting the pattern breaks Omolu.

**To Reproduce**

```
ormolu 'src/**/*.hs'
```
does not work and returns the following error: `ormolu: src/**/*.hs: openFile: does not exist (No such file or directory)`

**Environment**
 - macOS 11.2.1 
 - Version of the code: 0.2.0.0

**Additional context**

I am integrating `ormolu` into our development CLI which is written in haskell. `System.Process` automatically escapes arguments that have a pattern in them which is breaking ormolu.

**Comment by amesgen** [comment]
I think this is expected behavior: Ormolu does (intentionally) not specially handle globbing patterns, so you did probably previously rely on glob expansion of your shell.

`proc` from `System.Process` does not escape its argument, but rather does not run them through a shell where they could be expanded. There are multiple approaches how to work around this, e.g. using a Haskell globbing implementation like [Glob](https://hackage.haskell.org/package/Glob) or using `shell` instead of `proc`:

![screenshot-2021-09-12T18:58:38+02:00-62xK](https://user-images.githubusercontent.com/15369874/132996211-46c8cf0b-2201-4c01-8207-d7cc83bd7a6f.png)

**Comment by shinzui** [comment]
That makes sense. Thanks.

**Comment by amesgen** [comment]
Nice, thanks for the clear report!
