### ISSUE TITLE
ormolu puts function argument haddocks on their own line

### ISSUE THREAD

**Issue by mitchellwrosen** [tweag/ormolu#80]
Example input:

```haskell
foo
  :: Int -- ^ Documentation
  -> Bool
foo _ = True
```

After running `ormolu` over it:

```haskell
foo
  :: Int
  -> -- ^ Documentation
  Bool
foo _ = True
```

**Comment by mitchellwrosen** [comment]
I have done some `Debug.Trace`-ing, I think the problem might be in the `commentFollowsElt` function.

When run on the input file:

```haskell
foo
  :: Int -- ^ Hi
  -> Bool
```

the function is called three times.

---

## 1

On the element

```haskell
foo
```

with next element

```haskell
     Int -- ^ Hi
  -> Bool
```

and enclosing element

```haskell
foo
  :: Int -- ^ Hi
  -> Bool
```

we compute

```
goesAfter = True
logicallyFollows = True
noEltBetween = False
continuation = False
supersedesParentElt = False
```

---

## 2

On the element

```haskell
     Int
```

with next element

```haskell
     Bool
```

and enclosing element

```haskell
     Int
```
we compute

```
goesAfter = True
logicallyFollows = True
noEltBetween = True
continuation = False
supersedesParentElt = False
```

---

## 3

On the element

```haskell
     Int
```

with next element

```haskell
     Bool
```

and enclosing element

```haskell
     Int -- ^ Hi
  -> Bool
```
we compute

```
goesAfter = True
logicallyFollows = True
noEltBetween = True
continuation = False
supersedesParentElt = False
```

---

Hope that helps!

**Comment by mitchellwrosen** [comment]
Changing

```haskell
    supersedesParentElt =
      case meSpn of
        Nothing -> True
        Just espn ->
          let startColumn = srcLocCol . realSrcSpanStart
          in abs (startColumn espn - startColumn l)
               > abs (startColumn ref - startColumn l)
```

to

```haskell
    supersedesParentElt =
      case meSpn of
        Nothing -> True
        Just espn ->
          let startColumn = srcLocCol . realSrcSpanStart
          in abs (startColumn espn - startColumn l)
               >= abs (startColumn ref - startColumn l)
```

(note: `>` to `>=`)

fixes this particular example, but breaks some other tests. Example:

```haskell
       >>>>>>>>>>>>>>>>>>>>>> expected (first pass):
       -- | Something.
       data Foo
         = Foo
             Int
             Int
           -- ^ Foo
         | Bar
             Bool
             Bool
           -- ^ Bar

       >>>>>>>>>>>>>>>>>>>>>> but got:
       -- | Something.
       data Foo
         = Foo
             Int
             Int
             -- ^ Foo
         | Bar
             Bool
             Bool
             -- ^ Bar
```

so perhaps this tricky function ought to get a bit trickier.

**Comment by mrkkrp** [comment]
Yeah, this is a particularly subtle stuff. Let's see if I can fix it tonight.

**Comment by mrkkrp** [comment]
OK, not tonight.

But the problem is clear: we enter with `locate` (or some version of it) the same span twice. So the algorithm sees an element with identical enclosing element and get consumed as heck. Of course, that's not what I kept in mind writing `commentFollowsElt`.

Why not just check if enclosing span is the same as current (reference) span we're trying to attach comment to and forbid popping of comments in that case? Well that works, and we can skip popping the comment that way, but that's what the bug is about: we should pop it right after `Int`, otherwise it'll be popped *before* `Bool`.

And if we go the other way and say that "let's pop that comment if enclosing and reference spans match", then we might be just popping it at wrong moment because **this way we don't have info about the right enclosing element, because it was replaced by this copy of reference span**. This is important.

Here:

https://github.com/tweag/ormolu/blob/mk%2F80-fix-comment-placement/src/Ormolu/Printer/Combinators.hs#L102

we set enclosing element. Something should be adjusted here to avoid duplication in enclosing and reference spans. There are several alternative solutions, but I'm getting sleepy and so I'm leaving this to a later hacking session.
