### ISSUE TITLE
Executable generation sometimes fails for MacOS

### ISSUE THREAD

**Issue by mrkkrp** [tweag/ormolu#804]
As publishing 0.3.1.0 revealed GitHub has switched its MacOS runners from 10.15 to 11.6 which has broken generation of standalone executable for Mac. Generation fails with following error message:

```
Please specify now the directory where this library can be found (or write 'quit' to abort):
libSystem.B.dylib does not exist. Try again
```

(Repeated indefinitely.)

We need to figure out how to fix this.

**Comment by amesgen** [comment]
For the record: This is currently not an issue due to the workaround in #807 by building on macOS 10.15. The particular issue mentioned above vanishes when using a recent version of macdylibbundler (see https://github.com/NixOS/nixpkgs/pull/141874). Instead (but only on macOS 11), the binary builds fine, but does not execute as a transitive dylib dependency is missing. This could be a bug in macdylibbundler, but I am not 100% sure.

**Comment by amesgen** [comment]
I fixed the macdylibbundler bug in 1.0.4 (see https://github.com/auriamg/macdylibbundler/pull/76), so we can remove our custom version

https://github.com/tweag/ormolu/blob/8f95c53b2a8c29db22d06c15ee46b42a8f5551e9/nix/pkgs.nix#L7-L15

when we bump nixpkgs again. See [here](https://github.com/amesgen/ormolu/actions/runs/1757991011) for a CI run building the binaries with this fix.

**Comment by mrkkrp** [comment]
:+1: Can you open a PR?

**Comment by amesgen** [comment]
Right now, we use the nixpkgs-unstable pin from haskell.nix, so I thought about delaying this when haskell.nix updates to a nixpkgs pin which includes macdylibbundler-1.0.4. Of course, we could use a separate nixpkgs just for macdylibbundler-1.0.4, but I think there is no urgency to do that.

What about reopening it to not forget to do this? Or do we want to move to 1.0.4 right now?

**Comment by mrkkrp** [comment]
Okay, let's wait till haskell.nix updates.

> What about reopening it to not forget to do this?

I think this issue is resolved and it is misleading to reopen it. We could create a separate issue though.
