### ISSUE TITLE
emacs-mode haskell-mode-stylish-haskell-args

### ISSUE THREAD

**Issue by LambdaThinker** [tweag/ormolu#888]
In emacs-mode, i've set the stylish program to ormolu.
When I run stylish buffer, i got:
_The --stdin-input-file option is necessary when using input
from stdin and accountingThe --stdin-input-file option is necessary when using input from stdin and accounting for .cabal files_

Then I try to set the haskell-mode-stylish-haskell-args 
But i don't know how to make it work

**Comment by amesgen** [comment]
The error you are seeing is due to the fact that since 0.5.0.0, looking for `.cabal` files is now enabled by default. There are two ways to fix your error:

 - Add `--no-cabal` to `haskell-mode-stylish-haskell-arg`; this way, Ormolu will not look for `.cabal` files, as before 0.5.0.0.
 - Try to pass `--stdin-input-file` when possible (and set `--no-cabal` otherwise), i.e. when `buffer-file-name` is non-`nil`. See https://github.com/vyorkin/ormolu.el/pull/15 for my PR how to do this in ormolu.el.

Does this resolve your question?

For details, see the [first bullet point under 0.5.0.0 in the CHANGELOG](https://github.com/tweag/ormolu/blob/master/CHANGELOG.md#ormolu-0500=).

**Comment by LambdaThinker** [comment]
I can't set `haskell-mode-stylish-haskell-arg`, it does not accept string input.

**Comment by amesgen** [comment]
`haskell-mode-stylish-haskell-arg` expects a list, see [here](https://github.com/haskell/haskell-mode/blob/fe3a8046aa1e1767ddc11a74e3d45bd9c614e655/haskell-commands.el#L49), so i.e. `("--no-cabal")`.
