### ISSUE TITLE
Squash warnings about Setup.hs

### ISSUE THREAD

**Issue by donatello** [tweag/ormolu#924]
**Is your feature request related to a problem? Please describe.**

Most packages use a `Setup.hs` which is not directly used by stack or cabal, but is used by `runhaskell` (as mentioned [here](https://cabal.readthedocs.io/en/3.6/cabal-package.html#pkg-field-build-type)). Ormolu always prints a warning for this file:

```
Found .cabal file myapp/myapp.cabal, but it did not mention myapp/Setup.hs
```

**Describe the solution you'd like**
Ormolu could recognize this as a known file when it finds a cabal file and simply attempt to format it.

**Describe alternatives you've considered**
I've tried marking Setup.hs as an extra source file:

```
extra-source-file:
    Setup.hs
```

but this does not squash the warning and I am not sure if this is appropriate.

**Comment by amesgen** [comment]
> Ormolu could recognize this as a known file when it finds a cabal file and simply attempt to format it.

Note that this message does not mean that Ormolu did not format the file. Rather, it means that Ormolu current logic couldn't find a corresponding `.cabal` file mentioning it, which is mostly for informational or debugging purposes.

But we certainly could special case `Setup.hs` in directories which also contain a `.cabal` file, and even also include package information based on [`setup-depends`](https://cabal.readthedocs.io/en/3.6/cabal-package.html#pkg-field-custom-setup-setup-depends) if present.

---

Also, as you hint at, in the huge majority of cases (i.e. non-ancient cabal version and `build-type: Simple`, which has been the default since `cabal-version: 2.2`), the `Setup.hs` file can simply be deleted without any consequence. `cabal init` also does no longer create `Setup.hs`.

**Comment by donatello** [comment]
> Also, as you hint at, in the huge majority of cases (i.e. non-ancient cabal version and build-type: Simple, which has been the default since cabal-version: 2.2), the Setup.hs file can simply be deleted without any consequence. cabal init also does no longer create Setup.hs.

Ah that's good - in most of my cases, I can remove this file then. 👍🏾
