### ISSUE TITLE
Third party infix fixities not recognized when shadow infix function from base

### ISSUE THREAD

**Issue by brandonchinn178** [tweag/ormolu#929]
**Describe the bug**

**To Reproduce**
Putting the following into `ormolu-live.tweag.io`:
```hs
import qualified Database.Persist.Esqueleto as E

foo =
  E.from $
    E.table
      `E.innerJoin` E.table
      `E.on` ( \(a :& b) ->
               a E.^. AField E.==. b E.^. BField
             )
```
gets formatted as
```hs
import qualified Database.Persist.Esqueleto as E

foo =
  E.from
    $ E.table
      `E.innerJoin` E.table
    `E.on` ( \(a :& b) ->
               a E.^. AField E.==. b E.^. BField
           )
```

**Expected behavior**
It should be
```diff
 import qualified Database.Persist.Esqueleto as E
 
 foo =
   E.from
     $ E.table
       `E.innerJoin` E.table
-    `E.on` ( \(a :& b) ->
-               a E.^. AField E.==. b E.^. BField
-           )
+      `E.on` ( \(a :& b) ->
+                 a E.^. AField E.==. b E.^. BField
+             )
```

**Environment**
 - OS name + version:
 - Version of the code:

**Additional context**

**Comment by mrkkrp** [comment]
It look like possibly `on` gets wrong fixity associated with it. Possibly `on` from `base`? https://hackage.haskell.org/package/base-4.17.0.0/docs/Data-Function.html#v:on

From what I remember this is a rather unfortunate case because functions and operators from base get prioritized over everything else. I don't think qualifiers like `E` are currently taken into account.

**Comment by brandonchinn178** [comment]
Thanks. Worked around for now by making an `E.on_` alias, since we use our own `Esqueleto` module that re-exports `Esqueleto` functions anyway. But it'd be great to see this improved
