### ISSUE TITLE
False positive - cabal doesn't have a ref to a source file

### ISSUE THREAD

**Issue by yaitskov** [tweag/ormolu#971]
ormolu 0.5.0.1 prints warning:

```
Found .cabal file napkin.cabal, but it did not mention integration-tests/haskell/Sleep.hs
```

meanwhile cabal specifies source directory:

```
hs-source-dirs: src
```

I thinks it should not look into directories not mentioned by cabal.

**Comment by amesgen** [comment]
Thanks for the report, this is expected behavior: There is not really a way for us to know whether a `.hs` file is intentionally not mentioned in a `.cabal` file (which might both be a hint that it might not be desirable to format, or that it *should* be mentioned in the `.cabal` file).

One thing we could to here is to prefix the message you describe as a "warning" with `Info: ` (or some other "soothing" phrase) to make clear that in general, there is nothing bad/wrong/unexpected about having these messages in your output; or making them opt-out or even opt-in.
